[env:esp32dev]
platform = espressif32@6.12.0

board = pico32
framework = arduino

lib_deps =
    https://github.com/fdivitto/FabGL.git

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCONFIG_ARDUHAL_LOG_COLORS
    -DARDUINO_RUNNING_CORE=1
    -DARDUINO_EVENT_RUNNING_CORE=1
    -O2

build_unflags =
    -DCONFIG_IDF_TARGET_ESP32
    -Wall
    -Wextra
    -DARDUINO_RUNNING_CORE
    -DARDUINO_EVENT_RUNNING_CORE

build_type = release